name: dartIntermediate
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: newre <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  http: ^0.12.0+1
  path: ^1.6.2

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0

analyzer:
  #   exclude:
  #     - path/to/excluded/files/**
  strong-mode: true
  language:
    enableSuperMixins: true
